s3fs.settings:
  type: config_object
  mapping:
    access_key:
      type: string
      label: 'Amazon Web Services Access Key'
    secret_key:
      type: string
      label: 'Amazon Web Services Secret Key'
    use_instance_profile:
      type: boolean
      label: 'Use EC2 Instance Profile Credentials'
    default_cache_config:
      type: string
      label: 'Default Cache Location'
    bucket:
      type: string
      label: 'S3 Bucket Name'
    region:
      type: string
      label: 'S3 Region'
    use_cname:
      type: boolean
      label: 'Enable CNAME'
    use_customhost:
      type: boolean
      label: 'Use a Custom Host'
    hostname:
      type: string
      label: 'Hostname'
    domain:
      type: string
      label: 'CDN Domain Name'
    cache_control_header:
      type: string
      label: 'S3 Object Cache-Control Header'
    encryption:
      type: string
      label: 'Server-Side Encryption'
    use_https:
      type: boolean
      label: 'Always serve files from S3 via HTTPS'
    ignore_cache:
      type: boolean
      label: 'Ignore the file metadata cache'
    use_s3_for_public:
      type: boolean
      label: 'Use S3 for public:// files'
    no_rewrite_cssjs:
      type: boolean
      label: 'Do not rewrite CSS/JS file paths'
    use_s3_for_private:
      type: boolean
      label: 'Use S3 for private:// files'
    root_folder:
      type: string
      label: 'Root Folder'
    presigned_urls:
      type: string
      label: 'Presigned URLs'
    saveas:
      type: string
      label: 'Force Save As'
    torrents:
      type: string
      label: 'Torrents'
