<?php

/**
 * Implements hook_theme().
 */
use Drupal\node\Entity\Node;
//use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\taxonomy\TermStorage;
use Drupal\Core\Entity;
function capital_news_cron(){
    _capital_news_get_news();
}
function _capital_news_get_news() {
    // Google 
    $google_tid = 178;
    // Company News
    $nodes = getNodesByType('company');
    foreach( $nodes as $node){
        getGoogleNews($node->getTitle(), 0, $google_tid, $node->get('field_short_name')->value); //@TODO
    }

    // Other Key words
    $keywords_terms = _capital_news_getTermsByVocabularies(['additional_orgs','hot_spots','oversee_spots','general_key_words']);
    foreach( $keywords_terms as $term){
        getGoogleNews($term->name, $term->tid, $google_tid);
    }
    return;
    $account_terms = _capital_news_getTermsByVocabulary( 'wechat_accounts');
    \Drupal::logger('capital-test')->notice(print_r($account_terms, true));
    $wechat_offical_tid = 0;
    foreach( $account_terms as $account_term){
        getWechatOfficalNews($account_term, $wechat_offical_tid);
    }
}
function getNodesByType($type){
    $query = \Drupal::entityQuery('node')
        ->condition('status', 1)
        ->condition('type', $type);
    $nids = $query->execute();
    return \Drupal::entityManager()->getStorage('node')->loadMultiple(array_values($nids));
}
function getGoogleNews($key, $key_tid, $search_type_tid, $or_key = null){
    $config = \Drupal::config('capital_news.settings');

    \Drupal::logger('capital-test')->notice(print_r('live google', true));
    $json = capital_common_get_rest_custom_search($key);
    \Drupal::logger('capital-test')->notice(print_r($json, true));
    if(isset($json->items)){
        $current_time = time();
        foreach($json->items as $result){
            preg_match('/^(\d+) (hours|day) ago (.+)/s', $result->htmlSnippet, $matches);
            if (count($matches) != 4){
                \Drupal::logger('capital-test')->warning(print_r($matches, true));
            }

            $approximate_timestamp = $current_time - ($matches[2] == 'hours'? 3600 * $matches[1] : 86400);
            $approximate_timestamp = str_replace('+00:00', '', date_format(date_timestamp_set(new DateTime("now", new DateTimeZone('Etc/GMT+0')), $approximate_timestamp), 'c'));
            $origin_tid = _capital_news_getTidByLinkAndVocabulary($result->displayLink);
            _capital_news_createNews($result->htmlTitle, str_replace('<br>', '', $matches[3]), $result->link, $approximate_timestamp, $origin_tid, $search_type_tid, $key_tid);
        }
    }
}

function getWechatOfficalNews($account_term, $search_type_tid){
    \Drupal::logger('capital-test')->notice(print_r("wechat", true));
    //$account_name = trim(_capital_news_getTermDescriptionByTerm($account_term));
    $json = capital_common_get_wechat_offical_test_search($account_name);
    foreach($json->content as $result){
        _capital_news_createNews($result->title, $result->summary, $result->url, str_replace(' ', 'T', $result->date), $account_term->tid, $search_type_tid, 0,  $result->content);
    }
}

function _capital_news_getTermsByVocabularies($vids){
    $terms = array();
    foreach ( $vids as $vid){
        $terms =$terms +  \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    }
    return $terms;
}
function _capital_news_getTidByNameAndVocabulary($name, $vid){
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    foreach($terms as $term){
        if($term->name == $name){
            return $term->tid;
        }
    }
}
function _capital_news_getTidByLinkAndVocabulary($link){
    $db = \Drupal::database();
    $result = $db->select('taxonomy_term__field_domain_link','l')->fields('l', ['entity_id'])->condition('bundle', 'news_orgins')->condition('field_domain_link_value', '%' .  $db->escapeLike($link) . '%', 'LIKE')->execute()->fetchAll();
    return count($result) == 1? $result[0]->entity_id: 0;  //@TODO
}
function _capital_news_createNews($title, $description, $link, $timestamp, $origin_tid,  $type_tid, $key_tid, $content = null){
    \Drupal::logger('capital-test')->notice(print_r($key_tid, true));
    \Drupal::logger('capital-test')->notice(print_r('sdf', true));
    $db = \Drupal::database();
    $result = $db->select('node__field_news_link','l')->fields('l', ['entity_id'])->condition('field_news_link_uri', $link)->execute()->fetchAll();
    if (count($result)  > 0 ){
        $db = \Drupal::database();
        $links = $db->select('node__field_key_words','k')->fields('k', ['entity_id'])->condition('entity_id', $result[0]->entity_id)->condition('field_key_words_target_id', $key_tid)->execute()->fetchAll();
        if (count($links)  == 0 ){
            $node = Node::load($result[0]->entity_id);
            $node->field_key_words[] = $key_tid;
            $node->save();
        }
    } elseif (count($result) == 0){

        $node = Node::create([
            'type' => 'news',
            'created' => REQUEST_TIME,
            'changed' => REQUEST_TIME,
            'uid' => 1,
            'title' => $title,
            'field_title' =>[
                'value' => $title,
                'format' => 'full_html'
            ],
            'field_description' =>[
                'value' => $description,
                'format' => 'full_html'
            ],
            'field_news_link' =>[
                'uri' => $link,
            ],
            'field_content' =>[
                'value' => $content,
                'format' => 'full_html'
            ],
            'field_news_origin' => [$origin_tid],
            'field_search_type' =>[ $type_tid],
            'field_key_words' =>[$key_tid],
            'field_approximate_time' =>[
                'value' => $timestamp,
            ],
        ]);
        $node->save();
    }
}
function capital_news_theme() {
    $items = [
        'news_element' => [
            'render element' => 'element',
        ],
    ];
    return $items;
}

