<?php

/**
 * Implements hook_theme().
 */
use Drupal\node\Entity\Node;
//use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\taxonomy\TermStorage;
function capital_news_theme() {
    $items = [
        'news_element' => [
            'render element' => 'element',
        ],
    ];
    return $items;
}

function capital_news_cron(){
    \Drupal::logger('capital-test')->notice(print_r('live cron', true));
    _capital_news_get_news();
}
function _capital_news_get_news() {
    $account_terms = _capital_news_getTermsByVocabulary( 'wechat_accounts');
    \Drupal::logger('capital-test')->notice(print_r($account_terms, true));
    $wechat_offical_tid = 44;
    foreach( $account_terms as $account_term){
        getWechatOfficalNews($account_term, $wechat_offical_tid);
    }
    $keywords_terms = _capital_news_getTermsByVocabulary( 'key_words');
    $google_tid = 42;
    foreach( $keywords_terms as $keyword_term){
        getGoogleNews($keyword_term, $google_tid);
    }
}

function getGoogleNews($key_term, $search_type_tid){
    $config = \Drupal::config('capital_news.settings');

    \Drupal::logger('capital-test')->notice(print_r('live sdfsdfsearch', true));
    $json = capital_common_get_rest_custom_search($key_term->name);
    \Drupal::logger('capital-test')->notice(print_r($json, true));
    $current_time = time();
    foreach($json->items as $result){
        preg_match('/^(\d+) (hours|day) ago (.+)/s', $result->htmlSnippet, $matches);
        if (count($matches) != 4){

            \Drupal::logger('capital-test')->warning(print_r($matches, true));
        }

        $approximate_timestamp = $current_time - ($matches[2] == 'hours'? 3600 * $matches[1] : 86400);
        $approximate_timestamp = str_replace('+00:00', '', date_format(date_timestamp_set(new DateTime("now", new DateTimeZone('Etc/GMT+0')), $approximate_timestamp), 'c'));
        $origin_tid = _capital_news_getTidByDescriptionAndVocabulary($result->displayLink, 'news_orgins');
        _capital_news_createNews($result->htmlTitle, str_replace('<br>', '', $matches[3]), $result->link, $approximate_timestamp, $origin_tid, $search_type_tid, $key_term->tid);
    }
}

function getWechatOfficalNews($account_term, $search_type_tid){
    \Drupal::logger('capital-test')->notice(print_r("wechatsfsdf", true));
    \Drupal::logger('capital-test')->notice(print_r($account_term->description__value, true));
    $account_name = trim(_capital_news_getTermDescriptionByTerm($account_term));
    \Drupal::logger('capital-test')->notice(print_r($account_name, true));
    $json = capital_common_get_wechat_offical_test_search($account_name);
    \Drupal::logger('capital-test')->notice(print_r($json, true));
    foreach($json->content as $result){
        _capital_news_createNews($result->title, $result->summary, $result->url, str_replace(' ', 'T', $result->date), $account_term->tid, $search_type_tid, 0,  $result->content);
    }
}

function _capital_news_getTermsByVocabulary( $vid){
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    return $terms;
}
function _capital_news_getTidByNameAndVocabulary($name, $vid){
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    foreach($terms as $term){
        if($term->name == $name){
            return $term->tid;
        }
    }
}
function _capital_news_getTidByDescriptionAndVocabulary($description, $vid){
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    foreach($terms as $term){
        if($term->description__value == '<p>' . $description . '</p>'){
            return $term->tid;
        }
    }
}
function _capital_news_getTermDescriptionByTerm($term){
    return str_replace(['<p>', '</p>'], ['', ''], $term->description__value);
}
function _capital_news_createNews($title, $description, $link, $timestamp, $origin_tid,  $type_tid, $key_tid, $content = null){
    \Drupal::logger('capital-test')->notice(print_r("whhhhechat", true));
    $db = \Drupal::database();

    $result = $db->select('node__field_news_link','l')->fields('l', ['field_news_link_uri'])->condition('field_news_link_uri', $link)->execute()->fetchAllKeyed();
    if (count($result)  == 0){

        $node = Node::create([
            'type' => 'news',
            'created' => REQUEST_TIME,
            'changed' => REQUEST_TIME,
            'uid' => 1,
            'title' => $title,
            'field_title' =>[
                'value' => $title,
                'format' => 'full_html'
            ],
            'field_description' =>[
                'value' => $description,
                'format' => 'full_html'
            ],
            'field_news_link' =>[
                'uri' => $link,
            ],
            'field_content' =>[
                'value' => $content,
                'format' => 'full_html'
            ],
            'field_news_orgin' => [$origin_tid],
            'field_search_type' =>[ $type_tid],
            'field_key_word' =>[$key_tid],
            'field_approximate_time' =>[
                'value' => $timestamp,
            ],
        ]);
        $node->save();
    }
}
