<?php

/**
 * @file
 * Allows users to create and organize company information.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function capital_company_form_node_company_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#after_build'][] = 'capital_company_after_build';
}

/**
 * Update the website field value if no protocol is provided
 */
function capital_company_after_build(array $form, FormStateInterface $form_state) {
  if (isset($form['field_website']['widget'][0]['uri'])) {
    $uri = $form['field_website']['widget'][0]['uri']['#value'];
    if (!empty($uri) && parse_url($uri, PHP_URL_SCHEME) === NULL) {
      $uri_with_http = 'http://' . $uri;
      $form['field_website']['widget'][0]['uri']['#value'] = $uri_with_http;
    }
  }
  return $form;
}

/**
 * Implements hook_ENTITY_TYPE_presave() for node entities.
 *
 * Update the field collection item weight by date
 */
function capital_company_node_presave(EntityInterface $entity) {
  $collection_fields = array(
    array(
      'bundle' => 'company',
      'field_name' => 'field_asset_under_management',
      'sort_by' => 'field_data_collection_date',
    ),
    array(
      'bundle' => 'company',
      'field_name' => 'field_total_staff',
      'sort_by' => 'field_data_collection_date',
    ),
    array(
      'bundle' => 'company',
      'field_name' => 'field_researcher_staff',
      'sort_by' => 'field_data_collection_date',
    ),
  );
  capital_common_field_collection_sort($entity, $collection_fields);
}

