<?php

/**
 * @file
 * Allows users to create and organize company information.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function capital_company_form_node_company_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#after_build'][] = 'capital_company_after_build';
}

/**
 * Update the website field value if no protocol is provided
 */
function capital_company_after_build(array $form, FormStateInterface $form_state) {
  if (isset($form['field_website']['widget'][0]['uri'])) {
    $uri = $form['field_website']['widget'][0]['uri']['#value'];
    if (!empty($uri) && parse_url($uri, PHP_URL_SCHEME) === NULL) {
      $uri_with_http = 'http://' . $uri;
      $form['field_website']['widget'][0]['uri']['#value'] = $uri_with_http;
    }
  }
  return $form;
}
