<?php

/**
 * Implements hook_theme().
 */
function capital_common_get_rest_api($url, $headers = array()) {
  \Drupal::logger('capital-rest')->notice('URL ' . print_r($url, true));
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_REFERER, "capital-dev");
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
  $body = curl_exec($ch);
  curl_close($ch);

  if($body == null){
    \Drupal::logger('capital-rest')->notice('No return, invalid url ' . print_r($url, true));
  }

  return json_decode($body);
}
function capital_common_get_rest_custom_search($key, $orterms = null, $sort = 'date') {
  if( empty($key)){
    return;
  }
  $encoded_key = strpos($key, ' ') !== false? implode('+', array_map('_capital_common_wrap_search_key', explode(' ', $key))): '"' . urlencode($key) . '"';
  $encoded_key = implode('+', array_map('_capital_common_wrap_search_key', explode(' ', $key)));
  $config = \Drupal::config('capital_news.settings');

  if($config->get('search.api_pool') == null){
    $api_pool = [
      [
        'cx_token' => '004400752527919370638:64owq-rlmuw',
        'key_token' => 'AIzaSyB406FpOxPYJFYVdNambqiHCAPexkBaqJE',
      ],
      [
        'cx_token' => '003694133148730748554:kuvoapkccge',
        'key_token'  => 'AIzaSyAppfuBlfh65dfelZ4jtW7oYaWu41y1z1E',
      ],

    ];
    \Drupal::service('config.factory')->getEditable('capital_news.settings')->set('search.api_pool', $api_pool)->save();
  } else {
    $api_pool = $config->get('search.api_pool');
  }

  $api_index = $config->get('search.api_index') == null ? 0: $config->get('search.api_index');
  $url = 'https://www.googleapis.com/customsearch/v1?key=key_token&cx=cx_token&filter=1&dateRestrict=d1&q=' . $encoded_key; 
  if($sort){
    $url = $url . '&sort=' . $sort;
  }
  if($orterms){
    $url = $url . '&orTerms=' . (strpos($orterms, ' ') !== false? implode('+', array_map('_capital_common_wrap_search_key', explode(' ', $orterms))): '"' . urlencode($orterms) . '"');
  }
  $results = capital_common_get_rest_api(str_replace(array_keys($api_pool[$api_index]), array_values($api_pool[$api_index]), $url));
  if(isset($results->error)){
    if($results->error->code == 403){
      $next_index = $api_index + 1 == count($api_pool)? 0: $api_index + 1;
      $results = capital_common_get_rest_api(str_replace(array_keys($api_pool[$next_index]), array_values($api_pool[$next_index]), $url));
      \Drupal::service('config.factory')->getEditable('capital_news.settings')->set('search.api_index', $next_index)->save();

      if(isset($results->error)){
        \Drupal::logger('capital-rest')->error($results->error->code == 403? 'Meet Google API limits!' : 'Error ' . print_r($results, true));
      }
    } else{
      \Drupal::logger('capital-rest')->error('Error ' . print_r($results, true));
    }
  }
  return $results;
}
function capital_common_get_wechat_search($key){
  $encoded_key = strpos($key, ' ') !== false? implode('+', array_map('_capital_common_wrap_search_key', explode(' ', $key))): '"' . urlencode($key) . '"';
  $encoded_key = implode('+', array_map('_capital_common_wrap_search_key', explode(' ', $key)));
  $url = "http://52.78.11.123/keyword-day/" . $encoded_key;
  $results = capital_common_get_rest_api($url);
  \Drupal::logger('capital-wechat')->error( print_r($results, true));
  return $results;
}
function _capital_common_wrap_search_key($key){
  return '"' . urlencode($key) . '"';
}
function capital_common_get_wechat_offical_search($account_name) {
  $url = "http://52.78.11.123/account/" . urlencode($account_name);
  return (capital_common_get_rest_api($url));
}
function capital_common_get_wechat_offical_test_search($account_name) {
  $url = "http://api.aerchi.com/weixin/api.php?wxID=" . $account_name . "&key=FR2sIR7jULp2dVhw2CURrSVfhjvgGVlLNK2C6Vshy3IQhDJL+G2uqw";
  return (capital_common_get_rest_api($url));
}
